mqadmin/YmatouMQAdmin.WebApp2/Controllers/AdminMQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YmatouMQAdmin.Domain.IRepository;
using YmatouMQAdmin.Domain.Specifications;
using YmatouMQAdmin.Repository;
using YmatouMQNet4.Configuration;
using YmatouMQAdmin.WebApp2.Models;
using System.Collections;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using System.Configuration;
using Ymatou.CommonService;
using System.Diagnostics;
using YmatouMessageBusClientNet4;
using YmatouMessageBusClientNet4.Dto;
using System.IO;
using System.Net;
using System.Threading.Tasks;
using System.Text;
using YmatouMQAdmin.WebApp2.Authorize;
using System.Reflection;
using YmatouMQ.Common.Extensions;
using YmatouMQ.Common.Extensions.Serialization;
using YmatouMQMessageMongodb.Domain.Specifications;

namespace YmatouMQAdmin.WebApp2.Controllers
{
    [CustomerAuth]
    public class AdminMQController : Controller
    {

        private static void _JsonSettings()
        {
            Newtonsoft.Json.JsonConvert.DefaultSettings = () =>
            {
                return new JsonSerializerSettings
                {
                    DefaultValueHandling = DefaultValueHandling.Ignore,
                    NullValueHandling = NullValueHandling.Ignore,
                    Formatting = Formatting.None,
                    TypeNameHandling = TypeNameHandling.None
                };
            };
        }

        private bool IsDisplayDictionaryControl
        {
            get
            {
                var flag = ConfigurationManager.AppSettings["IsDisplayDictionaryControl"];
                if (flag != null)
                {
                    return flag.ToString() == "true" ? true : false;
                }
                else
                {
                    return false;
                }
            }
        }

        public string MQConfigurationDB
        {
            get
            {

                var _MQConfigurationDB = ConfigurationManager.AppSettings["MQConfigurationDB"];
                if (_MQConfigurationDB != null)
                {
                    return _MQConfigurationDB.ToString();
                }
                else
                {
                    return "MQ_Configuration_201505";
                }
            }
        }

        //
        public string MQAppDomainTable
        {
            get
            {

                var _MQAppDomainTable = ConfigurationManager.AppSettings["MQAppDomainTable"];
                if (_MQAppDomainTable != null)
                {
                    return _MQAppDomainTable.ToString();
                }
                else
                {
                    return "MQ_Appdomain_Cfg";
                }
            }
        }
        //

        public string MQDefaultTable
        {
            get
            {

                var _MQDefaultTable = ConfigurationManager.AppSettings["MQDefaultTable"];
                if (_MQDefaultTable != null)
                {
                    return _MQDefaultTable.ToString();
                }
                else
                {
                    return "MQ_Default_Cfg";
                }
            }
        }
        //
        public string MQAppCfgTable
        {
            get
            {

                var _MQAppCfgTable = ConfigurationManager.AppSettings["MQAppCfgTable"];
                if (_MQAppCfgTable != null)
                {
                    return _MQAppCfgTable.ToString();
                }
                else
                {
                    return "MQ_App_Cfg";
                }
            }
        }
        private List<string> ContextTypeArray
        {
            get
            {
                List<string> list = new List<string>();

                var contextType = ConfigurationManager.AppSettings["ContextTypeArray"];
                if (contextType != null)
                {
                    if (!contextType.ToString().Contains("未设置"))
                    {
                        list.Add("未设置");
                    }
                    var array = contextType.ToString().Split(',');
                    foreach (var context in array)
                    {
                        list.Add(context);
                    }
                }
                else
                {
                    list.Add("application/json");
                }
                if (!list.Contains("未设置"))
                {
                    list.Add("未设置");
                }
                return list;
            }
        }
        private List<string> ContentEncodingArray
        {
            get
            {
                List<string> list = new List<string>();

                var ContentEncoding = ConfigurationManager.AppSettings["ContentEncodingArray"];
                if (ContentEncoding != null)
                {
                    if (!ContentEncoding.ToString().Contains("未设置"))
                    {
                        list.Add("未设置");
                    }
                    var array = ContentEncoding.ToString().Split(',');
                    foreach (var Content in array)
                    {
                        list.Add(Content);
                    }
                }
                else
                {
                    list.Add("UTF-8");
                }

                if (!list.Contains("未设置"))
                {
                    list.Add("未设置");
                }
                return list;
            }
        }

        private List<string> httpType
        {
            get
            {
                List<string> list = new List<string>();

                var httpType = ConfigurationManager.AppSettings["httpType"];
                if (httpType != null)
                {
                    if (!httpType.ToString().Contains("未设置"))
                    {
                        list.Add("未设置");
                    }
                    var array = httpType.ToString().Split(',');
                    foreach (var type in array)
                    {
                        list.Add(type);
                    }
                }
                else
                {
                    list.Add("POST");
                    list.Add("GET");
                }
                if (!list.Contains("未设置"))
                {
                    list.Add("未设置");
                }
                return list;
            }
        }
        private Dictionary<string, int> RetryCount
        {
            get
            {
                Dictionary<string, int> dic = new Dictionary<string, int>();
                var _RetryCount = ConfigurationManager.AppSettings["RetryCount"];
                if (_RetryCount != null)
                {
                    var counts = _RetryCount.ToString().Split(',');
                    foreach (var count in counts)
                    {
                        dic.Add(count == "-1" ? "未设置" : count, int.Parse(count));
                    }
                }
                else
                {
                    dic.Add("1", 1);
                    dic.Add("2", 2);
                }
                return dic;
            }
        }

        private List<int> DomainConnectionPool
        {
            get
            {
                List<int> list = new List<int>();
                var domainConnectionPool = ConfigurationManager.AppSettings["DomainConnectionPool"];
                if (domainConnectionPool != null)
                {
                    var pools = domainConnectionPool.ToString().Split(',');
                    foreach (var pool in pools)
                    {
                        list.Add(int.Parse(pool));
                    }
                }
                else
                {
                    list.Add(1);
                    list.Add(2);
                    list.Add(3);
                }
                return list;
            }

        }
        public Dictionary<string, int> RetryMillisecond
        {
            get
            {
                Dictionary<string, int> dic = new Dictionary<string, int>();
                var _RetryMillisecond = ConfigurationManager.AppSettings["RetryMillisecond"];
                if (_RetryMillisecond != null)
                {
                    var counts = _RetryMillisecond.ToString().Split(',');
                    foreach (var count in counts)
                    {
                        dic.Add(count == "-1" ? "未设置" : count, int.Parse(count));
                    }
                }
                else
                {
                    dic.Add("500", 500);
                    dic.Add("1000", 1000);
                }
                return dic;
            }
        }

        public Dictionary<string, int> IsRetry
        {
            get
            {
                Dictionary<string, int> dic = new Dictionary<string, int>();
                var _IsRetry = ConfigurationManager.AppSettings["IsRetry"];
                if (_IsRetry != null)
                {
                    var counts = _IsRetry.ToString().Split(',');
                    foreach (var count in counts)
                    {
                        if (count == "-1")
                        {
                            dic.Add("未设置", -1);
                        }
                        if (count == "0")
                        {
                            dic.Add("不补发", 0);
                        }
                        if (count == "1")
                        {
                            dic.Add("补发", 1);
                        }
                    }
                }
                else
                {
                    dic.Add("未设置", -1);
                    dic.Add("不补发", 0);
                    dic.Add("补发", 1);
                }
                return dic;
            }
        }

        public Dictionary<string, int> buffer
        {
            get
            {

mqadmin/YmatouMQAdmin.WebApp2/Views/AdminMQ/AppDefault.cshtml
@{
    ViewBag.Title = "修改配置信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<div class="page-header">
        <span>根据应用ID，业务场景修改配置信息</span>
    </div>*@

<div class="container">
    @using (Html.BeginForm("EditApp", "AdminMQ", FormMethod.Post, new { @class = "form-inline" }))
    {
        <fieldset class="scheduler-border">
            <legend class="scheduler-border">编辑具体配置</legend>
            <div id="_form" class="form-group">
                <label for="AppId">AppID</label>
                <select id="AppId" name="AppId" class="selectpicker form-control" data-style="btn-primary">
                    <option value="default">请选择应用ID</option>
                    @foreach (var v in TempData["AppList"] as List<string>)
                    {
                        <option value="@v">@v</option>
                    }
                </select>
                <div id="query" class="form-group" style="display:none">
                    <label for="code">Code</label>
                    <select id="code" name="code" class="selectpicker form-control" data-style="btn-info"></select>
                    <div id="button">
                        <input type="submit" value="编辑" id="query_btn" class="btn btn-primary" role="button" />
                    </div>
                </div>
            </div>
            <p></p>
        </fieldset>
    }
</div>
<script type="text/javascript">
    $(function () {
        $("#query_btn").click(function () {
            if ($("#code").val() == null || $("#AppId").val() == "default") {
                busalert('请选择AppId和Code');
                return false;
            }
        });
        $("#AppId").change(function () {
            var _appId = $("#AppId").val();
            $("#code").empty();
            $.post("/AdminMQ/AppSearch?appId=" + _appId, function (data) {
                if (data.success) {
                    $.each(data.codeList, function (i, item) {
                        $("<option></option>").val(item["Value"]).text(item["Text"]).appendTo($("#code"))
                    })
                    if (data.count == 0) {
                        $("#CreateCodePanel").css('display', 'inline');
                        $("#button").css('display', 'none');
                    }
                    else {
                        $("#CreateCodePanel").css('display', 'none');
                        $("#button").css('display', 'inline');
                    }
                    $("#query").css('display', 'inline');
                }
            })
        })
    })

</script>

mqadmin/YmatouMQAdmin.WebApp2/Views/AdminMQ/AppGlobal.cshtml
@{
    ViewBag.Title = "AppGlobal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @using (Html.BeginForm("EditCurrentApp", "AdminMQ", FormMethod.Post, new { @class = "form-inline" }))
    {
        <fieldset class="scheduler-border">
            <legend class="scheduler-border">编辑消息配置JSON</legend>

            <div id="form" class="form-group">
                <label for="AppId">AppID</label>
                <select id="appId" name="appId" class="selectpicker form-control" data-style="btn-primary">
                    <option value="default">请选择应用ID</option>
                    @foreach (var v in TempData["AppList"] as List<string>)
                    {
                        <option value="@v">@v</option>
                    }
                </select>

                <input type="submit" value="编辑" class="btn btn-primary" />
            </div>
            <p></p>
        </fieldset>
    }
</div>

mqadmin/YmatouMQAdmin.WebApp2/Views/AdminMQ/CallBackIndex.cshtml
@{
    ViewBag.Title = "回调业务配置";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    @using (Html.BeginForm("EditCallbackConfiguration", "AdminMQ", FormMethod.Post, new { @class = "form-inline" }))
    {
        <fieldset class="scheduler-border">
            <legend class="scheduler-border">根据应用ID，业务场景修改回调业务配置</legend>

            <div id="mainDiv" class="form-group">

                <label for="AppId">AppID</label>
                <select id="appId" name="appId" class="selectpicker form-control" data-style="btn-primary">
                    <option value="default">请选择应用ID</option>
                    @foreach (var v in TempData["AppList"] as List<string>)
                    {
                        <option value="@v">@v</option>
                    }
                </select>

                <div id="query" class="form-group" style="display:none">
                    <label for="code">Code</label>
                    <select id="code" name="code" class="selectpicker form-control" data-style="btn-info"></select>

                    <div id="button">

                        <input type="submit" value="编辑" id="editbtn" class="btn btn-primary" />
                    </div>
                </div>

            </div>
            <p></p>
        </fieldset>
    }
</div>

<script type="text/javascript">

    $(function () {
        $("#editbtn").click(function () {
            if ($("#appId").val() == "default" || $("#code").val() == null) {
                busalert("请选择AppId和Code");
                return false;
            }
        });

        var div = $("#mainDiv");
        $("#appId").change(function () {
            var _appId = $("#appId").val();

            $("#code").empty();

            $.post("/AdminMQ/AppSearch?appId=" + _appId, function (data) {

                if (data.success) {
                    $.each(data.codeList, function (i, item) {
                        $("<option></option>").val(item["Value"]).text(item["Text"]).appendTo($("#code"))
                    })

                    if (data.count == 0) {
                        div.find("#CreateCodePanel").css('display', 'inline');
                        div.find("#button").css('display', 'none');
                    }
                    else {
                        div.find("#CreateCodePanel").css('display', 'none');
                        div.find("#button").css('display', 'inline');
                    }

                    div.find("#query").css('display', 'inline');
                }
            })
        })
    })

</script>

mqadmin/YmatouMQAdmin.WebApp2/Views/AdminMQ/DomainIndex.cshtml
@{
    ViewBag.Title = "新增Domain";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">
    <hr />
    @using (Html.BeginForm("SaveNewDomainAppCfg", "AdminMQ", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <fieldset class="scheduler-border">
            <legend class="scheduler-border">队列分组关联</legend>
            <div id="form" class="control-group">
                <label for="appId" class="col-sm-2 control-label">AppID</label>
                <div class="col-sm-10">
                    <select id="appId" name="appId" class="selectpicker form-control" data-style="btn-primary">
                        <option value="default">请选择应用ID</option>
                        @foreach (var v in TempData["AppList"] as List<string>)
                        {
                            <option value="@v">@v</option>
                        }
                    </select>
                    <p></p>
                </div>
                <label for="owerHost" class="col-sm-2 control-label">关联HOST</label>
                <div id="owerHostdiv" class="col-sm-10">
                    <input type="text" name="owerHost" id="owerHost" class="form-control" />
                    <p class="text-left help-block  text-error"><small>可选,填写IP后2段位，多个ip间英文逗号分割</small></p>
                </div>
                <table width="100%">
                    <tr>
                        <td class="col-sm-2 control-label" valign="top"><label for="codelist" id="code_lable">选择Code</label></td>
                        <td align="left">
                            <div style="float: left; text-indent:0.7em" id="codelist" class="form-inline">
                                <p></p>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <p id="msg"></p>
        </fieldset>
        <div id="addbtndiv" style="display: none">
            <input id="savequeue" class="btn btn-primary" type="submit" value="关联并启动队列" />
        </div>
        <p></p>
    }
</div>
    <script type="text/javascript">

        $(function () {
            $("#appId").change(function () {
                $("#codelist").empty();
                $("#msg").empty();
                $.post("/AdminMQ/AppDomainSearch?appId=" + $("#appId").val(), function (data) {
                    if (data.success) {
                        $.each(data.codeList, function (i, item) {
                            $("<label id='code' class='checkbox-inline' for='" + item["Value"] + " '><input type='checkbox' id=" + item["Value"] + " name='checkboxList' value=" + item["Value"] + ">" + item["Text"] + "</input>  </label>").appendTo("#codelist");
                        });
                        if (data.count == 0) {
                            $("#addbtndiv").css('display', 'none');
                            $("#codelist").html("<p classs='text-left text-error'><small style='color:red'>" + $("#appId").val() + "没有可关联的队列</small></p>");
                        }
                        else {
                            $("#addbtndiv").css('display', 'inline');
                        }
                    }
                })
            })

            $("#savequeue").click(function () {
                $("input:checkbox").each(function () {
                    if ($(this).is(":checked")) {
                        var _v = $(this).val();
                        _v += ":true"
                        $(this).val(_v);
                    }
                })
            })
        })

    </script>

mqadmin/YmatouMQAdmin.WebApp2/Views/AdminMQ/EditAppQueueStatusJson.cshtml
@{
    ViewBag.Title = "EditAppQueueStatusJson";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    @using (Html.BeginForm("SaveEditAppQueueStatusJson", "AdminMQ", FormMethod.Post, new { @class = "form-inline" }))
    {
        <fieldset class="scheduler-border">
            <legend class="scheduler-border">编辑队列JSON</legend>

            <div id="form" class="form-group">

                <label for="domainId">AppID</label>
                <select id="domainId" name="domainId" class="selectpicker form-control" data-style="btn-primary">
                    <option value="default">请选择应用ID</option>
                    @foreach (var v in TempData["QueueStatusJson"] as List<string>)
                    {
                        <option value="@v">@v</option>
                    }
                </select>

                <input type="submit" value="编辑" class="btn btn-primary" />

            </div>
            <p></p>
        </fieldset>
    }
 </div>

mqadmin/YmatouMQAdmin.WebApp2/Views/AdminMQ/EditCallbackConfiguration.cshtml
@model List<YmatouMQNet4.Configuration.CallbackConfiguration>
@{
    ViewBag.Title = "编辑回调业务配置";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    @using (Ajax.BeginForm("SaveCallbackConfiguration", "AdminMQ"
         , new AjaxOptions
    {
        OnFailure = "busalert",
        OnBegin = "onBegin",
        OnComplete = "",
        OnSuccess = ""
    }
        , new { @class = "form-horizontal" }))
    {
        <input type="hidden" id="appId" name="appId" value="@ViewBag.appId" />

        <input type="hidden" id="code" name="code" value="@ViewBag.code" />

        @Html.Partial("_CallBackList", Model)

        <div id="button">
            <input id="save" type="submit" class="btn btn-primary" value="保存" />
        </div>
    }
</div>

mqadmin/YmatouMQAdmin.WebApp2/Views/AdminMQ/EditCurrentApp.cshtml
@{
    ViewBag.Title = "EditCurrentApp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    string app = (string)ViewBag.GlobalApp;
}
<div class="container">
    <input type="hidden" id="appHidden" value="@app" />
    <fieldset class="scheduler-border">
        <legend class="scheduler-border">编辑消息配置JSON</legend>
        <div class="col-sm-10 control-group" style="width:100%">
            <textarea id="appString" class="form-control" name="appString" style="width:100%;height:600px;"></textarea>
            <p></p>
        </div>
    </fieldset>
    <div id="button">
        <input id="submit" type="submit" class="btn btn-primary" value="保存" role="button" />
        <a href="javascript:history.back()" class="btn btn-warning">返回</a>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        var h = $("#appHidden").val();
        $("#appString").html(h);
        $("#submit").click(function () {
            var appString = $("#appString").val();
            if (appString == "null") {
                busalert("请填写消息JSON");
                return false;
            }
            try {
                JSON.parse(appString);
            }
            catch (e) {
                busalert("字符串格式不符合JSON格式，请检查");
                return false;
            }
            var formatdata = { appContent: appString };
            $.ajax({
                url: "/AdminMQ/EditGlobalApp",
                type: "POST",
                dataType: "json",
                data: formatdata,
                // data: JSON.stringify(formatData),
                contentType: "application/x-www-form-urlencoded; charset=UTF-8",
                success: function (data) {
                    if (data.success) {
                        busalert("保存成功");
                    }
                    else {
                        busalert(data.msg);
                    }
                }

            });
            //$.post("/AdminMQ/EditGlobalApp?appString=" + appString, function (data)
            //{
            //    if(data.success)
            //    {
            //        alert("保存成功");
            //    }
            //    else
            //    {
            //        alert("保存失败");
            //    }
            //})
        })
    })
</script>

mqadmin/YmatouMQAdmin.WebApp2/Views/AdminMQ/EditDomain.cshtml
@model YmatouMQNet4.Configuration.AppdomainConfiguration

@{
    ViewBag.Title = "编辑 Domain";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">

    <hr />
    @using (Ajax.BeginForm("EditSaveDomainCfg", "AdminMQ", new AjaxOptions
    {
        OnFailure = "busalert",
        OnBegin = "onBegin",
        OnComplete = "",
        OnSuccess = ""
    }, new { @class = "form-horizontal" }))
    {
        <fieldset class="scheduler-border">
            <legend class="scheduler-border">队列状态（启动，停止），归属Host分组，管理</legend>
            <div class="control-group">
                <label for="DomainName" class="col-sm-2 control-label">AppID</label>
                <div class="col-sm-10">
                    <input type="text" id="DomainName" name="DomainName" class="form-control list-group-item disabled" readonly="readonly" value="@Model.DomainName" />
                    <p></p>

                </div>
                <label for="ownerhost" class="col-sm-2 control-label">分组状态</label>
                <div class="col-sm-10">
                    @Html.DropDownListFor(m => m.Status, ViewBag.DomainActionItems as List<SelectListItem>, new { @class = "form-control" })
                    <p class="text-left help-block  text-error"><small>选择Remove状态则停止该分组下的所有队列实例</small></p>
                </div>
                <label for="ownerhost" class="col-sm-2 control-label">归属Host</label>
                <div class="col-sm-10">
                    <input type="text" id="ownerhost" name="Host" class="form-control" value="@Model.Host" />
                    <p class="text-left help-block  text-error"><small>填写IP后两段，多个host间英文逗号分割</small></p>
                </div>
            </div>

            @if (Model.Items != null)
            {
                @Html.Partial("_domainItem", Model.Items)
            }

        </fieldset>
        <div id="button">
            <input type="submit" value="保存" class="btn btn-primary" /> @Html.ActionLink("返回到列表页面", "AppdomainList", null, new { @class = "btn btn-warning" })
        </div>
    }
</div>

mqadmin/YmatouMQAdmin.WebApp2/Views/AdminMQ/TestMessage.cshtml
@{
    ViewBag.Title = "TestMessage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container">  
    <div class="form-horizontal">
        @*@using (Html.BeginForm("PublishMessageTest", "AdminMQ", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {*@
        <fieldset class="scheduler-border">
            <legend class="scheduler-border">测试发送消息</legend>
            <div class="control-group">
                <label for="AppId" class="col-sm-2 control-label">AppID</label>
                <div id="AppIdDiv" class="col-sm-10">
                    <select id="AppId" name="AppId" class="selectpicker form-control" data-style="btn-primary">
                        <option value="_default">请选择应用ID</option>
                        @foreach (var v in TempData["AppList"] as IEnumerable<string>)
                        {
                        <option value="@v">@v</option>
                        }
                    </select>
                    <p id="_appidalert" class="text-left help-block  text-error"></p>
                </div>
                <label for="Code" class="col-sm-2 control-label">Code</label>
                <div id="code" class="col-sm-10">
                    <select id="Code" name="Code" class="selectpicker form-control" data-style="btn-primary">
                        <option value="_default">请选择Code</option>
                    </select>
                    <p id="_codealert" class="text-left help-block  text-error"></p>
                </div>
                <label for="Repeatcount" class="col-sm-2 control-label">重复次数</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" value="1" id="Repeatcount" name="Repeatcount" />
                    <p></p>
                </div>
                <label for="pubResult" class="col-sm-2 control-label">发送结果</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control list-group-item disabled" id="pubResult" name="pubResult" />
                    <p></p>
                </div>
                <label for="Msgcontent" class="col-sm-2 control-label">消息内容</label>
                <div class="col-sm-10">
                    <textarea class="form-control disabled" id="Msgcontent" style="margin: 0px -0.671875px 0px 0px; width: 100%; height: 378px;" name="msgcontent"></textarea>
                    <p class="text-left help-block  text-error">输入JSON格式</p>
                </div>
            </div>
        </fieldset>
        <div id="button">
            <input id="pubmessage" class="btn btn-primary" type="button" value="发送消息" />
        </div>
    </div>
    @* } *@
</div>

<script type="text/javascript">
    $(function () {
        $("#AppId").change(function () {
            if ($("#AppId").val() != "_default") {
                $("#_appidalert").empty();
            }
            $("#Code").empty();
            $("#pubResult").empty();
            $.post("/AdminMQ/AppSearch?appId=" + $("#AppId").val(), function (data) {
                if (data.success) {
                    $.each(data.codeList, function (i, item) {
                        $("<option></option>").val(item["Value"]).text(item["Text"]).appendTo($("#Code"))
                    })
                    if (data.count == 0) {
                        $("#pubmessage").attr('disabled', 'true');
                    }
                    else {
                        $("#pubmessage").removeAttr('disabled');
                    }
                }
            })
        });
        $("#pubmessage").click(function () {
            if ($("#AppId").val() == "_default") {
                $("#_appidalert").html("<small>请选择APPID</small>");
                return false;
            }
            if ($("#Code").val() == "_default") {
                $("#_codealert").html("<small>请选择Code</small>");
                return false;
            }
            try {
                JSON.parse($("#Msgcontent").val());
            }
            catch (e) {
                $("#pubResult").val("字符串格式不符合JSON格式，请检查");
                return false;
            }
            $("#pubResult").val("发送中...");
            $.post("/AdminMQ/PublishMessageTest?AppId=" + $("#AppId").val() + "&Code=" + $("#Code").val() + "&Msgcontent=" + $("#Msgcontent").val() + "&Repeatcount=" + $("#Repeatcount").val(), function (data) {
                $("#pubResult").val(data);
            })
        });
    });
</script>